// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Tests
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// Test1 - Use 'Test1Params' to pass parameters into this method.
        /// </summary>
        public void Test1()
        {
            #region Variable Declarations
            WpfButton uIAllePersonenButton = this.UIMainWindowWindow.UIAllePersonenButton;
            WpfText uIGibbText = this.UIMainWindowWindow.UIPlvPersonsCustom.UIDataGridTable.UIItem1Row.UIGibbCell.UIGibbText;
            WpfEdit uITxtChairEdit = this.UIMainWindowWindow.UIItemCustom.UITxtChairEdit;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UIItemCustom.UISpeichernButton;
            WpfText uIHauerterPaulaText = this.UIMainWindowWindow.UIPlvPersonsCustom1.UIDataGridTable.UIItem2Row.UIHauerterPaulaCell.UIHauerterPaulaText;
            WpfEdit uITxtChairEdit1 = this.UIMainWindowWindow.UIItemCustom1.UITxtChairEdit;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UIItemCustom1.UISpeichernButton;
            WpfText uIGibbText1 = this.UIMainWindowWindow.UIPlvPersonsCustom2.UIDataGridTable.UIItem3Row.UIGibbCell.UIGibbText;
            WpfEdit uITxtChairEdit2 = this.UIMainWindowWindow.UIItemCustom2.UITxtChairEdit;
            WpfButton uISpeichernButton2 = this.UIMainWindowWindow.UIItemCustom2.UISpeichernButton;
            WpfCell uICuenetFredCell = this.UIMainWindowWindow.UIPlvPersonsCustom3.UIDataGridTable.UIItem4Row.UICuenetFredCell;
            WpfComboBox uICbTischComboBox = this.UIMainWindowWindow.UIItemCustom3.UICbTischComboBox;
            WpfEdit uITxtChairEdit3 = this.UIMainWindowWindow.UIItemCustom3.UITxtChairEdit;
            WpfButton uISpeichernButton3 = this.UIMainWindowWindow.UIItemCustom3.UISpeichernButton;
            WpfText uITestIncText = this.UIMainWindowWindow.UIPlvPersonsCustom4.UIDataGridTable.UIItem5Row.UITestIncCell.UITestIncText;
            WpfEdit uITxtChairEdit4 = this.UIMainWindowWindow.UIItemCustom4.UITxtChairEdit;
            WpfButton uISpeichernButton4 = this.UIMainWindowWindow.UIItemCustom4.UISpeichernButton;
            WpfText uITestIncText1 = this.UIMainWindowWindow.UIPlvPersonsCustom5.UIDataGridTable.UIItem6Row.UITestIncCell.UITestIncText;
            WpfEdit uITxtChairEdit5 = this.UIMainWindowWindow.UIItemCustom5.UITxtChairEdit;
            WpfButton uISpeichernButton5 = this.UIMainWindowWindow.UIItemCustom5.UISpeichernButton;
            WpfText uITestIncText2 = this.UIMainWindowWindow.UIPlvPersonsCustom6.UIDataGridTable.UIItem7Row.UITestIncCell.UITestIncText;
            WpfEdit uITxtChairEdit6 = this.UIMainWindowWindow.UIItemCustom6.UITxtChairEdit;
            WpfButton uISpeichernButton6 = this.UIMainWindowWindow.UIItemCustom6.UISpeichernButton;
            WpfText uITestIncText3 = this.UIMainWindowWindow.UIPlvPersonsCustom7.UIDataGridTable.UIItem8Row.UITestIncCell.UITestIncText;
            WpfEdit uITxtChairEdit7 = this.UIMainWindowWindow.UIItemCustom7.UITxtChairEdit;
            WpfButton uISpeichernButton7 = this.UIMainWindowWindow.UIItemCustom7.UISpeichernButton;
            WpfButton uITischordnungButton = this.UIMainWindowWindow.UITischordnungButton;
            #endregion

            // Click 'Alle Personen' button
            Mouse.Click(uIAllePersonenButton, new Point(60, 9));

            // Double-Click 'gibb' label
            Mouse.DoubleClick(uIGibbText, new Point(52, 11));

            // Type '1' in 'txtChair' text box
            uITxtChairEdit.Text = this.Test1Params.UITxtChairEditText;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton, new Point(68, 12));

            // Double-Click 'Hauerter Paula' label
            Mouse.DoubleClick(uIHauerterPaulaText, new Point(82, 3));

            // Type '2' in 'txtChair' text box
            uITxtChairEdit1.Text = this.Test1Params.UITxtChairEditText1;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(46, 5));

            // Double-Click 'gibb' label
            Mouse.DoubleClick(uIGibbText1, new Point(47, 6));

            // Type '3' in 'txtChair' text box
            uITxtChairEdit2.Text = this.Test1Params.UITxtChairEditText2;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton2, new Point(66, 10));

            // Double-Click 'Cuenet Fred' cell
            Mouse.DoubleClick(uICuenetFredCell, new Point(140, 10));

            // Select '1' in 'cbTisch' combo box
            uICbTischComboBox.SelectedItem = this.Test1Params.UICbTischComboBoxSelectedItem;

            // Type '4' in 'txtChair' text box
            uITxtChairEdit3.Text = this.Test1Params.UITxtChairEditText3;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton3, new Point(62, 15));

            // Double-Click 'Test Inc.' label
            Mouse.DoubleClick(uITestIncText, new Point(27, 7));

            // Type '1' in 'txtChair' text box
            uITxtChairEdit4.Text = this.Test1Params.UITxtChairEditText4;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton4, new Point(128, 6));

            // Double-Click 'Test Inc.' label
            Mouse.DoubleClick(uITestIncText1, new Point(48, 5));

            // Type '2' in 'txtChair' text box
            uITxtChairEdit5.Text = this.Test1Params.UITxtChairEditText5;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton5, new Point(55, 9));

            // Double-Click 'Test Inc.' label
            Mouse.DoubleClick(uITestIncText2, new Point(51, 8));

            // Type '3' in 'txtChair' text box
            uITxtChairEdit6.Text = this.Test1Params.UITxtChairEditText6;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton6, new Point(46, 19));

            // Double-Click 'Test Inc.' label
            Mouse.DoubleClick(uITestIncText3, new Point(72, 6));

            // Type '4' in 'txtChair' text box
            uITxtChairEdit7.Text = this.Test1Params.UITxtChairEditText7;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton7, new Point(74, 14));

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(62, 13));
        }
        
        /// <summary>
        /// Testcase2 - Use 'Testcase2Params' to pass parameters into this method.
        /// </summary>
        public void Testcase2()
        {
            #region Variable Declarations
            WpfButton uITischordnungButton = this.UIMainWindowWindow.UITischordnungButton;
            WpfCustom uIItemCustom = this.UIMainWindowWindow.UIItemCustom8.UISpeichernButton.UIItemCustom;
            WpfListItem uIItem5ListItem = this.UIMainWindowWindow.UIItem5ListItem;
            WpfCustom uIItemCustom1 = this.UIMainWindowWindow.UIItemCustom9.UISpeichernButton.UIItemCustom;
            WpfCustom uIItemCustom11 = this.UIMainWindowWindow.UIItemCustom10.UISpeichernButton.UIItemCustom1;
            WpfText uIHerrText = this.UIMainWindowWindow.UIPlvPersonsCustom.UIDataGridTable.UIItem1Row.UIHerrCell.UIHerrText;
            WpfEdit uITxtChairEdit = this.UIMainWindowWindow.UIItemCustom.UITxtChairEdit;
            WpfButton uISpeichernButton = this.UIMainWindowWindow.UIItemCustom.UISpeichernButton;
            WpfText uIFrauText = this.UIMainWindowWindow.UIPlvPersonsCustom1.UIDataGridTable.UIItem2Row.UIFrauCell.UIFrauText;
            WpfEdit uITxtChairEdit1 = this.UIMainWindowWindow.UIItemCustom1.UITxtChairEdit;
            WpfButton uISpeichernButton1 = this.UIMainWindowWindow.UIItemCustom1.UISpeichernButton;
            WpfText uIHerrText1 = this.UIMainWindowWindow.UIPlvPersonsCustom2.UIDataGridTable.UIItem3Row.UIHerrCell.UIHerrText;
            WpfEdit uITxtChairEdit2 = this.UIMainWindowWindow.UIItemCustom2.UITxtChairEdit;
            WpfButton uISpeichernButton2 = this.UIMainWindowWindow.UIItemCustom2.UISpeichernButton;
            WpfText uITsbeText = this.UIMainWindowWindow.UIPlvPersonsCustom3.UIDataGridTable.UIItem4Row.UITsbeCell.UITsbeText;
            WpfComboBox uICbTischComboBox = this.UIMainWindowWindow.UIItemCustom3.UICbTischComboBox;
            WpfEdit uITxtChairEdit3 = this.UIMainWindowWindow.UIItemCustom3.UITxtChairEdit;
            WpfButton uISpeichernButton3 = this.UIMainWindowWindow.UIItemCustom3.UISpeichernButton;
            WpfText uITestIncText = this.UIMainWindowWindow.UIPlvPersonsCustom4.UIDataGridTable.UIItem5Row.UITestIncCell.UITestIncText;
            WpfComboBox uICbTischComboBox1 = this.UIMainWindowWindow.UIItemCustom4.UICbTischComboBox;
            WpfEdit uITxtChairEdit4 = this.UIMainWindowWindow.UIItemCustom4.UITxtChairEdit;
            WpfButton uISpeichernButton4 = this.UIMainWindowWindow.UIItemCustom4.UISpeichernButton;
            WpfCustom uIItemCustom2 = this.UIMainWindowWindow.UIItemCustom61.UISpeichernButton.UIItemCustom;
            WpfComboBox uICbTischComboBox2 = this.UIMainWindowWindow.UIItemCustom5.UICbTischComboBox;
            WpfButton uISpeichernButton5 = this.UIMainWindowWindow.UIItemCustom5.UISpeichernButton;
            WpfComboBox uICbTischComboBox3 = this.UIMainWindowWindow.UIItemCustom6.UICbTischComboBox;
            WpfButton uISpeichernButton6 = this.UIMainWindowWindow.UIItemCustom6.UISpeichernButton;
            WpfCustom uIItemCustom3 = this.UIMainWindowWindow.UIItemCustom10.UISpeichernButton.UIItemCustom;
            WpfComboBox uICbTischComboBox4 = this.UIMainWindowWindow.UIItemCustom7.UICbTischComboBox;
            WpfButton uISpeichernButton7 = this.UIMainWindowWindow.UIItemCustom7.UISpeichernButton;
            #endregion

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(40, 14));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom, new Point(835, 178));

            // Click '5' list item
            Mouse.Click(uIItem5ListItem, new Point(46, 12));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom1, new Point(931, 178));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom11, new Point(464, 233));

            // Double-Click 'Herr' label
            Mouse.DoubleClick(uIHerrText, new Point(104, 1));

            // Type '1' in 'txtChair' text box
            uITxtChairEdit.Text = this.Testcase2Params.UITxtChairEditText;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton, new Point(63, 7));

            // Double-Click 'Frau' label
            Mouse.DoubleClick(uIFrauText, new Point(35, 5));

            // Type '2' in 'txtChair' text box
            uITxtChairEdit1.Text = this.Testcase2Params.UITxtChairEditText1;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton1, new Point(120, 16));

            // Double-Click 'Herr' label
            Mouse.DoubleClick(uIHerrText1, new Point(97, 6));

            // Type '3' in 'txtChair' text box
            uITxtChairEdit2.Text = this.Testcase2Params.UITxtChairEditText2;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton2, new Point(50, 21));

            // Double-Click 'tsbe' label
            Mouse.DoubleClick(uITsbeText, new Point(65, 0));

            // Select '1' in 'cbTisch' combo box
            uICbTischComboBox.SelectedItem = this.Testcase2Params.UICbTischComboBoxSelectedItem;

            // Type '4' in 'txtChair' text box
            uITxtChairEdit3.Text = this.Testcase2Params.UITxtChairEditText3;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton3, new Point(81, 15));

            // Double-Click 'Test Inc.' label
            Mouse.DoubleClick(uITestIncText, new Point(46, 11));

            // Select '1' in 'cbTisch' combo box
            uICbTischComboBox1.SelectedItem = this.Testcase2Params.UICbTischComboBoxSelectedItem1;

            // Type '5' in 'txtChair' text box
            uITxtChairEdit4.Text = this.Testcase2Params.UITxtChairEditText4;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton4, new Point(72, 6));

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(26, 6));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom2, new Point(683, 260));

            // Select '2' in 'cbTisch' combo box
            uICbTischComboBox2.SelectedItem = this.Testcase2Params.UICbTischComboBoxSelectedItem2;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton5, new Point(78, 11));

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(55, 7));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom, new Point(734, 290));

            // Select '2' in 'cbTisch' combo box
            uICbTischComboBox3.SelectedItem = this.Testcase2Params.UICbTischComboBoxSelectedItem3;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton6, new Point(78, 8));

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(65, 5));

            // Click first custom control next to 'Speichern' button
            Mouse.Click(uIItemCustom3, new Point(715, 348));

            // Select '2' in 'cbTisch' combo box
            uICbTischComboBox4.SelectedItem = this.Testcase2Params.UICbTischComboBoxSelectedItem4;

            // Click 'Speichern' button
            Mouse.Click(uISpeichernButton7, new Point(77, 10));

            // Click 'Tischordnung' button
            Mouse.Click(uITischordnungButton, new Point(67, 10));
        }
        
        #region Properties
        public virtual Test1Params Test1Params
        {
            get
            {
                if ((this.mTest1Params == null))
                {
                    this.mTest1Params = new Test1Params();
                }
                return this.mTest1Params;
            }
        }
        
        public virtual Testcase2Params Testcase2Params
        {
            get
            {
                if ((this.mTestcase2Params == null))
                {
                    this.mTestcase2Params = new Testcase2Params();
                }
                return this.mTestcase2Params;
            }
        }
        
        public UIMainWindowWindow UIMainWindowWindow
        {
            get
            {
                if ((this.mUIMainWindowWindow == null))
                {
                    this.mUIMainWindowWindow = new UIMainWindowWindow();
                }
                return this.mUIMainWindowWindow;
            }
        }
        #endregion
        
        #region Fields
        private Test1Params mTest1Params;
        
        private Testcase2Params mTestcase2Params;
        
        private UIMainWindowWindow mUIMainWindowWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Test1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Test1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText = "1";
        
        /// <summary>
        /// Type '2' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText1 = "2";
        
        /// <summary>
        /// Type '3' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText2 = "3";
        
        /// <summary>
        /// Select '1' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem = "1";
        
        /// <summary>
        /// Type '4' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText3 = "4";
        
        /// <summary>
        /// Type '1' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText4 = "1";
        
        /// <summary>
        /// Type '2' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText5 = "2";
        
        /// <summary>
        /// Type '3' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText6 = "3";
        
        /// <summary>
        /// Type '4' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText7 = "4";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'Testcase2'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class Testcase2Params
    {
        
        #region Fields
        /// <summary>
        /// Type '1' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText = "1";
        
        /// <summary>
        /// Type '2' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText1 = "2";
        
        /// <summary>
        /// Type '3' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText2 = "3";
        
        /// <summary>
        /// Select '1' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem = "1";
        
        /// <summary>
        /// Type '4' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText3 = "4";
        
        /// <summary>
        /// Select '1' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem1 = "1";
        
        /// <summary>
        /// Type '5' in 'txtChair' text box
        /// </summary>
        public string UITxtChairEditText4 = "5";
        
        /// <summary>
        /// Select '2' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem2 = "2";
        
        /// <summary>
        /// Select '2' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem3 = "2";
        
        /// <summary>
        /// Select '2' in 'cbTisch' combo box
        /// </summary>
        public string UICbTischComboBoxSelectedItem4 = "2";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMainWindowWindow : WpfWindow
    {
        
        public UIMainWindowWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MainWindow";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfButton UIAllePersonenButton
        {
            get
            {
                if ((this.mUIAllePersonenButton == null))
                {
                    this.mUIAllePersonenButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIAllePersonenButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnAllPersons";
                    this.mUIAllePersonenButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIAllePersonenButton;
            }
        }
        
        public UIPlvPersonsCustom UIPlvPersonsCustom
        {
            get
            {
                if ((this.mUIPlvPersonsCustom == null))
                {
                    this.mUIPlvPersonsCustom = new UIPlvPersonsCustom(this);
                }
                return this.mUIPlvPersonsCustom;
            }
        }
        
        public UIItemCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new UIItemCustom(this);
                }
                return this.mUIItemCustom;
            }
        }
        
        public UIPlvPersonsCustom1 UIPlvPersonsCustom1
        {
            get
            {
                if ((this.mUIPlvPersonsCustom1 == null))
                {
                    this.mUIPlvPersonsCustom1 = new UIPlvPersonsCustom1(this);
                }
                return this.mUIPlvPersonsCustom1;
            }
        }
        
        public UIItemCustom1 UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new UIItemCustom1(this);
                }
                return this.mUIItemCustom1;
            }
        }
        
        public UIPlvPersonsCustom2 UIPlvPersonsCustom2
        {
            get
            {
                if ((this.mUIPlvPersonsCustom2 == null))
                {
                    this.mUIPlvPersonsCustom2 = new UIPlvPersonsCustom2(this);
                }
                return this.mUIPlvPersonsCustom2;
            }
        }
        
        public UIItemCustom2 UIItemCustom2
        {
            get
            {
                if ((this.mUIItemCustom2 == null))
                {
                    this.mUIItemCustom2 = new UIItemCustom2(this);
                }
                return this.mUIItemCustom2;
            }
        }
        
        public UIPlvPersonsCustom3 UIPlvPersonsCustom3
        {
            get
            {
                if ((this.mUIPlvPersonsCustom3 == null))
                {
                    this.mUIPlvPersonsCustom3 = new UIPlvPersonsCustom3(this);
                }
                return this.mUIPlvPersonsCustom3;
            }
        }
        
        public UIItemCustom3 UIItemCustom3
        {
            get
            {
                if ((this.mUIItemCustom3 == null))
                {
                    this.mUIItemCustom3 = new UIItemCustom3(this);
                }
                return this.mUIItemCustom3;
            }
        }
        
        public UIPlvPersonsCustom4 UIPlvPersonsCustom4
        {
            get
            {
                if ((this.mUIPlvPersonsCustom4 == null))
                {
                    this.mUIPlvPersonsCustom4 = new UIPlvPersonsCustom4(this);
                }
                return this.mUIPlvPersonsCustom4;
            }
        }
        
        public UIItemCustom4 UIItemCustom4
        {
            get
            {
                if ((this.mUIItemCustom4 == null))
                {
                    this.mUIItemCustom4 = new UIItemCustom4(this);
                }
                return this.mUIItemCustom4;
            }
        }
        
        public UIPlvPersonsCustom5 UIPlvPersonsCustom5
        {
            get
            {
                if ((this.mUIPlvPersonsCustom5 == null))
                {
                    this.mUIPlvPersonsCustom5 = new UIPlvPersonsCustom5(this);
                }
                return this.mUIPlvPersonsCustom5;
            }
        }
        
        public UIItemCustom5 UIItemCustom5
        {
            get
            {
                if ((this.mUIItemCustom5 == null))
                {
                    this.mUIItemCustom5 = new UIItemCustom5(this);
                }
                return this.mUIItemCustom5;
            }
        }
        
        public UIPlvPersonsCustom6 UIPlvPersonsCustom6
        {
            get
            {
                if ((this.mUIPlvPersonsCustom6 == null))
                {
                    this.mUIPlvPersonsCustom6 = new UIPlvPersonsCustom6(this);
                }
                return this.mUIPlvPersonsCustom6;
            }
        }
        
        public UIItemCustom6 UIItemCustom6
        {
            get
            {
                if ((this.mUIItemCustom6 == null))
                {
                    this.mUIItemCustom6 = new UIItemCustom6(this);
                }
                return this.mUIItemCustom6;
            }
        }
        
        public UIPlvPersonsCustom7 UIPlvPersonsCustom7
        {
            get
            {
                if ((this.mUIPlvPersonsCustom7 == null))
                {
                    this.mUIPlvPersonsCustom7 = new UIPlvPersonsCustom7(this);
                }
                return this.mUIPlvPersonsCustom7;
            }
        }
        
        public UIItemCustom7 UIItemCustom7
        {
            get
            {
                if ((this.mUIItemCustom7 == null))
                {
                    this.mUIItemCustom7 = new UIItemCustom7(this);
                }
                return this.mUIItemCustom7;
            }
        }
        
        public WpfButton UITischordnungButton
        {
            get
            {
                if ((this.mUITischordnungButton == null))
                {
                    this.mUITischordnungButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUITischordnungButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnTableView";
                    this.mUITischordnungButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITischordnungButton;
            }
        }
        
        public UIItemCustom8 UIItemCustom8
        {
            get
            {
                if ((this.mUIItemCustom8 == null))
                {
                    this.mUIItemCustom8 = new UIItemCustom8(this);
                }
                return this.mUIItemCustom8;
            }
        }
        
        public WpfListItem UIItem5ListItem
        {
            get
            {
                if ((this.mUIItem5ListItem == null))
                {
                    this.mUIItem5ListItem = new WpfListItem(this);
                    #region Search Criteria
                    this.mUIItem5ListItem.SearchProperties[WpfListItem.PropertyNames.Name] = "5";
                    this.mUIItem5ListItem.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItem5ListItem;
            }
        }
        
        public UIItemCustom9 UIItemCustom9
        {
            get
            {
                if ((this.mUIItemCustom9 == null))
                {
                    this.mUIItemCustom9 = new UIItemCustom9(this);
                }
                return this.mUIItemCustom9;
            }
        }
        
        public UIItemCustom10 UIItemCustom10
        {
            get
            {
                if ((this.mUIItemCustom10 == null))
                {
                    this.mUIItemCustom10 = new UIItemCustom10(this);
                }
                return this.mUIItemCustom10;
            }
        }
        
        public UIItemCustom61 UIItemCustom61
        {
            get
            {
                if ((this.mUIItemCustom61 == null))
                {
                    this.mUIItemCustom61 = new UIItemCustom61(this);
                }
                return this.mUIItemCustom61;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIAllePersonenButton;
        
        private UIPlvPersonsCustom mUIPlvPersonsCustom;
        
        private UIItemCustom mUIItemCustom;
        
        private UIPlvPersonsCustom1 mUIPlvPersonsCustom1;
        
        private UIItemCustom1 mUIItemCustom1;
        
        private UIPlvPersonsCustom2 mUIPlvPersonsCustom2;
        
        private UIItemCustom2 mUIItemCustom2;
        
        private UIPlvPersonsCustom3 mUIPlvPersonsCustom3;
        
        private UIItemCustom3 mUIItemCustom3;
        
        private UIPlvPersonsCustom4 mUIPlvPersonsCustom4;
        
        private UIItemCustom4 mUIItemCustom4;
        
        private UIPlvPersonsCustom5 mUIPlvPersonsCustom5;
        
        private UIItemCustom5 mUIItemCustom5;
        
        private UIPlvPersonsCustom6 mUIPlvPersonsCustom6;
        
        private UIItemCustom6 mUIItemCustom6;
        
        private UIPlvPersonsCustom7 mUIPlvPersonsCustom7;
        
        private UIItemCustom7 mUIItemCustom7;
        
        private WpfButton mUITischordnungButton;
        
        private UIItemCustom8 mUIItemCustom8;
        
        private WpfListItem mUIItem5ListItem;
        
        private UIItemCustom9 mUIItemCustom9;
        
        private UIItemCustom10 mUIItemCustom10;
        
        private UIItemCustom61 mUIItemCustom61;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom : WpfCustom
    {
        
        public UIPlvPersonsCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable : WpfTable
    {
        
        public UIDataGridTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem1Row UIItem1Row
        {
            get
            {
                if ((this.mUIItem1Row == null))
                {
                    this.mUIItem1Row = new UIItem1Row(this);
                }
                return this.mUIItem1Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem1Row mUIItem1Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem1Row : WpfRow
    {
        
        public UIItem1Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "1";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIGibbCell UIGibbCell
        {
            get
            {
                if ((this.mUIGibbCell == null))
                {
                    this.mUIGibbCell = new UIGibbCell(this);
                }
                return this.mUIGibbCell;
            }
        }
        
        public UIHerrCell UIHerrCell
        {
            get
            {
                if ((this.mUIHerrCell == null))
                {
                    this.mUIHerrCell = new UIHerrCell(this);
                }
                return this.mUIHerrCell;
            }
        }
        #endregion
        
        #region Fields
        private UIGibbCell mUIGibbCell;
        
        private UIHerrCell mUIHerrCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGibbCell : WpfCell
    {
        
        public UIGibbCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIGibbText
        {
            get
            {
                if ((this.mUIGibbText == null))
                {
                    this.mUIGibbText = new WpfText(this);
                    #region Search Criteria
                    this.mUIGibbText.SearchProperties[WpfText.PropertyNames.Name] = "gibb";
                    this.mUIGibbText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIGibbText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIGibbText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHerrCell : WpfCell
    {
        
        public UIHerrCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Anrede";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIHerrText
        {
            get
            {
                if ((this.mUIHerrText == null))
                {
                    this.mUIHerrText = new WpfText(this);
                    #region Search Criteria
                    this.mUIHerrText.SearchProperties[WpfText.PropertyNames.Name] = "Herr";
                    this.mUIHerrText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIHerrText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIHerrText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom : WpfCustom
    {
        
        public UIItemCustom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom1 : WpfCustom
    {
        
        public UIPlvPersonsCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable1 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable1(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable1 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable1 : WpfTable
    {
        
        public UIDataGridTable1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem2Row UIItem2Row
        {
            get
            {
                if ((this.mUIItem2Row == null))
                {
                    this.mUIItem2Row = new UIItem2Row(this);
                }
                return this.mUIItem2Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem2Row mUIItem2Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem2Row : WpfRow
    {
        
        public UIItem2Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIHauerterPaulaCell UIHauerterPaulaCell
        {
            get
            {
                if ((this.mUIHauerterPaulaCell == null))
                {
                    this.mUIHauerterPaulaCell = new UIHauerterPaulaCell(this);
                }
                return this.mUIHauerterPaulaCell;
            }
        }
        
        public UIFrauCell UIFrauCell
        {
            get
            {
                if ((this.mUIFrauCell == null))
                {
                    this.mUIFrauCell = new UIFrauCell(this);
                }
                return this.mUIFrauCell;
            }
        }
        #endregion
        
        #region Fields
        private UIHauerterPaulaCell mUIHauerterPaulaCell;
        
        private UIFrauCell mUIFrauCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHauerterPaulaCell : WpfCell
    {
        
        public UIHauerterPaulaCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Name";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIHauerterPaulaText
        {
            get
            {
                if ((this.mUIHauerterPaulaText == null))
                {
                    this.mUIHauerterPaulaText = new WpfText(this);
                    #region Search Criteria
                    this.mUIHauerterPaulaText.SearchProperties[WpfText.PropertyNames.Name] = "Hauerter Paula";
                    this.mUIHauerterPaulaText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIHauerterPaulaText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIHauerterPaulaText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIFrauCell : WpfCell
    {
        
        public UIFrauCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Anrede";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIFrauText
        {
            get
            {
                if ((this.mUIFrauText == null))
                {
                    this.mUIFrauText = new WpfText(this);
                    #region Search Criteria
                    this.mUIFrauText.SearchProperties[WpfText.PropertyNames.Name] = "Frau";
                    this.mUIFrauText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIFrauText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIFrauText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom1 : WpfCustom
    {
        
        public UIItemCustom1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom2 : WpfCustom
    {
        
        public UIPlvPersonsCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable2 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable2(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable2 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable2 : WpfTable
    {
        
        public UIDataGridTable2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem3Row UIItem3Row
        {
            get
            {
                if ((this.mUIItem3Row == null))
                {
                    this.mUIItem3Row = new UIItem3Row(this);
                }
                return this.mUIItem3Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem3Row mUIItem3Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem3Row : WpfRow
    {
        
        public UIItem3Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "3";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIGibbCell1 UIGibbCell
        {
            get
            {
                if ((this.mUIGibbCell == null))
                {
                    this.mUIGibbCell = new UIGibbCell1(this);
                }
                return this.mUIGibbCell;
            }
        }
        
        public UIHerrCell1 UIHerrCell
        {
            get
            {
                if ((this.mUIHerrCell == null))
                {
                    this.mUIHerrCell = new UIHerrCell1(this);
                }
                return this.mUIHerrCell;
            }
        }
        #endregion
        
        #region Fields
        private UIGibbCell1 mUIGibbCell;
        
        private UIHerrCell1 mUIHerrCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIGibbCell1 : WpfCell
    {
        
        public UIGibbCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIGibbText
        {
            get
            {
                if ((this.mUIGibbText == null))
                {
                    this.mUIGibbText = new WpfText(this);
                    #region Search Criteria
                    this.mUIGibbText.SearchProperties[WpfText.PropertyNames.Name] = "gibb";
                    this.mUIGibbText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIGibbText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIGibbText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHerrCell1 : WpfCell
    {
        
        public UIHerrCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Anrede";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UIHerrText
        {
            get
            {
                if ((this.mUIHerrText == null))
                {
                    this.mUIHerrText = new WpfText(this);
                    #region Search Criteria
                    this.mUIHerrText.SearchProperties[WpfText.PropertyNames.Name] = "Herr";
                    this.mUIHerrText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIHerrText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUIHerrText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom2 : WpfCustom
    {
        
        public UIItemCustom2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom3 : WpfCustom
    {
        
        public UIPlvPersonsCustom3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable3 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable3(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable3 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable3 : WpfTable
    {
        
        public UIDataGridTable3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem4Row UIItem4Row
        {
            get
            {
                if ((this.mUIItem4Row == null))
                {
                    this.mUIItem4Row = new UIItem4Row(this);
                }
                return this.mUIItem4Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem4Row mUIItem4Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem4Row : WpfRow
    {
        
        public UIItem4Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "4";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCell UICuenetFredCell
        {
            get
            {
                if ((this.mUICuenetFredCell == null))
                {
                    this.mUICuenetFredCell = new WpfCell(this);
                    #region Search Criteria
                    this.mUICuenetFredCell.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Name";
                    this.mUICuenetFredCell.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICuenetFredCell;
            }
        }
        
        public UITsbeCell UITsbeCell
        {
            get
            {
                if ((this.mUITsbeCell == null))
                {
                    this.mUITsbeCell = new UITsbeCell(this);
                }
                return this.mUITsbeCell;
            }
        }
        #endregion
        
        #region Fields
        private WpfCell mUICuenetFredCell;
        
        private UITsbeCell mUITsbeCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITsbeCell : WpfCell
    {
        
        public UITsbeCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITsbeText
        {
            get
            {
                if ((this.mUITsbeText == null))
                {
                    this.mUITsbeText = new WpfText(this);
                    #region Search Criteria
                    this.mUITsbeText.SearchProperties[WpfText.PropertyNames.Name] = "tsbe";
                    this.mUITsbeText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITsbeText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITsbeText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom3 : WpfCustom
    {
        
        public UIItemCustom3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfComboBox UICbTischComboBox
        {
            get
            {
                if ((this.mUICbTischComboBox == null))
                {
                    this.mUICbTischComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUICbTischComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbTisch";
                    this.mUICbTischComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbTischComboBox;
            }
        }
        
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfComboBox mUICbTischComboBox;
        
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom4 : WpfCustom
    {
        
        public UIPlvPersonsCustom4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable4 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable4(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable4 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable4 : WpfTable
    {
        
        public UIDataGridTable4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem5Row UIItem5Row
        {
            get
            {
                if ((this.mUIItem5Row == null))
                {
                    this.mUIItem5Row = new UIItem5Row(this);
                }
                return this.mUIItem5Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem5Row mUIItem5Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem5Row : WpfRow
    {
        
        public UIItem5Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "5";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UITestIncCell UITestIncCell
        {
            get
            {
                if ((this.mUITestIncCell == null))
                {
                    this.mUITestIncCell = new UITestIncCell(this);
                }
                return this.mUITestIncCell;
            }
        }
        #endregion
        
        #region Fields
        private UITestIncCell mUITestIncCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestIncCell : WpfCell
    {
        
        public UITestIncCell(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITestIncText
        {
            get
            {
                if ((this.mUITestIncText == null))
                {
                    this.mUITestIncText = new WpfText(this);
                    #region Search Criteria
                    this.mUITestIncText.SearchProperties[WpfText.PropertyNames.Name] = "Test Inc.";
                    this.mUITestIncText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITestIncText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITestIncText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom4 : WpfCustom
    {
        
        public UIItemCustom4(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public WpfComboBox UICbTischComboBox
        {
            get
            {
                if ((this.mUICbTischComboBox == null))
                {
                    this.mUICbTischComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUICbTischComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbTisch";
                    this.mUICbTischComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbTischComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        
        private WpfComboBox mUICbTischComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom5 : WpfCustom
    {
        
        public UIPlvPersonsCustom5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable5 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable5(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable5 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable5 : WpfTable
    {
        
        public UIDataGridTable5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem6Row UIItem6Row
        {
            get
            {
                if ((this.mUIItem6Row == null))
                {
                    this.mUIItem6Row = new UIItem6Row(this);
                }
                return this.mUIItem6Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem6Row mUIItem6Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem6Row : WpfRow
    {
        
        public UIItem6Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "6";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UITestIncCell1 UITestIncCell
        {
            get
            {
                if ((this.mUITestIncCell == null))
                {
                    this.mUITestIncCell = new UITestIncCell1(this);
                }
                return this.mUITestIncCell;
            }
        }
        #endregion
        
        #region Fields
        private UITestIncCell1 mUITestIncCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestIncCell1 : WpfCell
    {
        
        public UITestIncCell1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITestIncText
        {
            get
            {
                if ((this.mUITestIncText == null))
                {
                    this.mUITestIncText = new WpfText(this);
                    #region Search Criteria
                    this.mUITestIncText.SearchProperties[WpfText.PropertyNames.Name] = "Test Inc.";
                    this.mUITestIncText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITestIncText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITestIncText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom5 : WpfCustom
    {
        
        public UIItemCustom5(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public WpfComboBox UICbTischComboBox
        {
            get
            {
                if ((this.mUICbTischComboBox == null))
                {
                    this.mUICbTischComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUICbTischComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbTisch";
                    this.mUICbTischComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbTischComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        
        private WpfComboBox mUICbTischComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom6 : WpfCustom
    {
        
        public UIPlvPersonsCustom6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable6 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable6(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable6 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable6 : WpfTable
    {
        
        public UIDataGridTable6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem7Row UIItem7Row
        {
            get
            {
                if ((this.mUIItem7Row == null))
                {
                    this.mUIItem7Row = new UIItem7Row(this);
                }
                return this.mUIItem7Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem7Row mUIItem7Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem7Row : WpfRow
    {
        
        public UIItem7Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "7";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UITestIncCell2 UITestIncCell
        {
            get
            {
                if ((this.mUITestIncCell == null))
                {
                    this.mUITestIncCell = new UITestIncCell2(this);
                }
                return this.mUITestIncCell;
            }
        }
        #endregion
        
        #region Fields
        private UITestIncCell2 mUITestIncCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestIncCell2 : WpfCell
    {
        
        public UITestIncCell2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITestIncText
        {
            get
            {
                if ((this.mUITestIncText == null))
                {
                    this.mUITestIncText = new WpfText(this);
                    #region Search Criteria
                    this.mUITestIncText.SearchProperties[WpfText.PropertyNames.Name] = "Test Inc.";
                    this.mUITestIncText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITestIncText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITestIncText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom6 : WpfCustom
    {
        
        public UIItemCustom6(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public WpfComboBox UICbTischComboBox
        {
            get
            {
                if ((this.mUICbTischComboBox == null))
                {
                    this.mUICbTischComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUICbTischComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbTisch";
                    this.mUICbTischComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbTischComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        
        private WpfComboBox mUICbTischComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIPlvPersonsCustom7 : WpfCustom
    {
        
        public UIPlvPersonsCustom7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonListView";
            this.SearchProperties[WpfControl.PropertyNames.AutomationId] = "plvPersons";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIDataGridTable7 UIDataGridTable
        {
            get
            {
                if ((this.mUIDataGridTable == null))
                {
                    this.mUIDataGridTable = new UIDataGridTable7(this);
                }
                return this.mUIDataGridTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridTable7 mUIDataGridTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIDataGridTable7 : WpfTable
    {
        
        public UIDataGridTable7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTable.PropertyNames.AutomationId] = "DataGrid";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UIItem8Row UIItem8Row
        {
            get
            {
                if ((this.mUIItem8Row == null))
                {
                    this.mUIItem8Row = new UIItem8Row(this);
                }
                return this.mUIItem8Row;
            }
        }
        #endregion
        
        #region Fields
        private UIItem8Row mUIItem8Row;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItem8Row : WpfRow
    {
        
        public UIItem8Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfRow.PropertyNames.Name] = "8";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UITestIncCell3 UITestIncCell
        {
            get
            {
                if ((this.mUITestIncCell == null))
                {
                    this.mUITestIncCell = new UITestIncCell3(this);
                }
                return this.mUITestIncCell;
            }
        }
        #endregion
        
        #region Fields
        private UITestIncCell3 mUITestIncCell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UITestIncCell3 : WpfCell
    {
        
        public UITestIncCell3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfCell.PropertyNames.ColumnHeader] = "Firma";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfText UITestIncText
        {
            get
            {
                if ((this.mUITestIncText == null))
                {
                    this.mUITestIncText = new WpfText(this);
                    #region Search Criteria
                    this.mUITestIncText.SearchProperties[WpfText.PropertyNames.Name] = "Test Inc.";
                    this.mUITestIncText.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITestIncText;
            }
        }
        #endregion
        
        #region Fields
        private WpfText mUITestIncText;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom7 : WpfCustom
    {
        
        public UIItemCustom7(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.PersonView";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfEdit UITxtChairEdit
        {
            get
            {
                if ((this.mUITxtChairEdit == null))
                {
                    this.mUITxtChairEdit = new WpfEdit(this);
                    #region Search Criteria
                    this.mUITxtChairEdit.SearchProperties[WpfEdit.PropertyNames.AutomationId] = "txtChair";
                    this.mUITxtChairEdit.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUITxtChairEdit;
            }
        }
        
        public WpfButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUISpeichernButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
                    this.mUISpeichernButton.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUISpeichernButton;
            }
        }
        
        public WpfComboBox UICbTischComboBox
        {
            get
            {
                if ((this.mUICbTischComboBox == null))
                {
                    this.mUICbTischComboBox = new WpfComboBox(this);
                    #region Search Criteria
                    this.mUICbTischComboBox.SearchProperties[WpfComboBox.PropertyNames.AutomationId] = "cbTisch";
                    this.mUICbTischComboBox.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUICbTischComboBox;
            }
        }
        #endregion
        
        #region Fields
        private WpfEdit mUITxtChairEdit;
        
        private WpfButton mUISpeichernButton;
        
        private WpfComboBox mUICbTischComboBox;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom8 : WpfCustom
    {
        
        public UIItemCustom8(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Tischordnung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UISpeichernButton UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new UISpeichernButton(this);
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UISpeichernButton mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpeichernButton : WpfButton
    {
        
        public UISpeichernButton(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TischView";
                    this.mUIItemCustom.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemCustom.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom9 : WpfCustom
    {
        
        public UIItemCustom9(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Tischordnung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UISpeichernButton1 UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new UISpeichernButton1(this);
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UISpeichernButton1 mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpeichernButton1 : WpfButton
    {
        
        public UISpeichernButton1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TischView";
                    this.mUIItemCustom.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemCustom.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom10 : WpfCustom
    {
        
        public UIItemCustom10(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Tischordnung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UISpeichernButton2 UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new UISpeichernButton2(this);
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UISpeichernButton2 mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpeichernButton2 : WpfButton
    {
        
        public UISpeichernButton2(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIItemCustom1
        {
            get
            {
                if ((this.mUIItemCustom1 == null))
                {
                    this.mUIItemCustom1 = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom1.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TischView";
                    this.mUIItemCustom1.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemCustom1.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemCustom1;
            }
        }
        
        public WpfCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TischView";
                    this.mUIItemCustom.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemCustom.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIItemCustom1;
        
        private WpfCustom mUIItemCustom;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIItemCustom61 : WpfCustom
    {
        
        public UIItemCustom61(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.Tischordnung";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public UISpeichernButton3 UISpeichernButton
        {
            get
            {
                if ((this.mUISpeichernButton == null))
                {
                    this.mUISpeichernButton = new UISpeichernButton3(this);
                }
                return this.mUISpeichernButton;
            }
        }
        #endregion
        
        #region Fields
        private UISpeichernButton3 mUISpeichernButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UISpeichernButton3 : WpfButton
    {
        
        public UISpeichernButton3(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfButton.PropertyNames.AutomationId] = "btnSave";
            this.WindowTitles.Add("MainWindow");
            #endregion
        }
        
        #region Properties
        public WpfCustom UIItemCustom
        {
            get
            {
                if ((this.mUIItemCustom == null))
                {
                    this.mUIItemCustom = new WpfCustom(this);
                    #region Search Criteria
                    this.mUIItemCustom.SearchProperties[WpfControl.PropertyNames.ClassName] = "Uia.TischView";
                    this.mUIItemCustom.SearchConfigurations.Add(SearchConfiguration.NextSibling);
                    this.mUIItemCustom.WindowTitles.Add("MainWindow");
                    #endregion
                }
                return this.mUIItemCustom;
            }
        }
        #endregion
        
        #region Fields
        private WpfCustom mUIItemCustom;
        #endregion
    }
}
